import { useState, type ReactNode } from "react";
import {
  Activity, ArrowRight, BarChart3, Bell, Bot, Check, ChevronDown, CircleAlert,
  Clock3, Cpu, Eye, Gauge, Hexagon, Layers3, LineChart, Menu, Network,
  ShieldCheck, Sparkles, TerminalSquare, Wrench, X, Zap,
} from "lucide-react";

const colors = {
  navy: "#102d4a", teal: "#078da8", cyan: "#72dce2", amber: "#e8a92c",
  mist: "#f3f8f8", ink: "#173b55", muted: "#607b89", line: "#d7e7e9",
};

function Mark({ inverse = false }: { inverse?: boolean }) {
  return <div className="flex items-center gap-2.5">
    <span className={`relative flex h-9 w-9 items-center justify-center ${inverse ? "text-cyan-300" : "text-[#078da8]"}`}>
      <Hexagon className="absolute h-9 w-9 stroke-[1.2]" /><Hexagon className="absolute h-5 w-5 fill-current/10 stroke-[1.6]" />
      <span className="absolute h-1.5 w-1.5 rounded-full bg-amber-300" />
    </span>
    <span className={`text-[21px] font-bold tracking-[-.07em] ${inverse ? "text-white" : "text-[#102d4a]"}`}>Beel<span className="text-[#078da8]">dings</span></span>
  </div>;
}
function Label({ children, light = false }: { children: ReactNode; light?: boolean }) {
  return <p className={`mb-4 flex items-center gap-2 font-mono text-[10px] font-bold uppercase tracking-[.2em] ${light ? "text-cyan-300" : "text-[#078da8]"}`}><span className="h-1.5 w-1.5 rounded-full bg-amber-400" />{children}</p>;
}
function ProofPanel() {
  const [tab, setTab] = useState(0);
  const reads = [
    ["O que está acontecendo?", "O Chiller 02 apresenta aumento de vibração desde 05:18. O padrão coincide com queda gradual de eficiência térmica."],
    ["Por que isso importa?", "Se a vibração continuar neste ritmo, a eficiência pode cair mais 11% nas próximas 3 horas. Há dois eventos semelhantes no histórico."],
    ["Qual é o próximo passo?", "Recomendo inspeção do conjunto de ventilação entre 07:10 e 07:35, antes do pico de demanda. A evidência já está organizada."],
  ];
  return <div className="relative overflow-hidden rounded-[24px] border border-[#2c5872] bg-[#102d4a] p-4 text-white shadow-[0_30px_70px_rgba(16,45,74,.2)] sm:p-6">
    <div className="absolute inset-0 opacity-30" style={{ backgroundImage: "linear-gradient(rgba(114,220,226,.12) 1px,transparent 1px),linear-gradient(90deg,rgba(114,220,226,.12) 1px,transparent 1px)", backgroundSize: "30px 30px" }} />
    <div className="relative flex items-center justify-between border-b border-white/10 pb-4"><div><p className="font-mono text-[9px] uppercase tracking-[.18em] text-cyan-300">BlueBee · parceiro de decisão</p><p className="mt-1 text-sm font-semibold">Torre Norte · São Paulo</p></div><span className="flex items-center gap-2 rounded-full bg-emerald-300/10 px-2.5 py-1 font-mono text-[9px] text-emerald-200"><span className="h-1.5 w-1.5 rounded-full bg-emerald-300" />AO VIVO</span></div>
    <div className="relative grid gap-3 py-5 sm:grid-cols-2"><div className="rounded-xl border border-white/10 bg-[#0b2943] p-4"><div className="flex justify-between text-[10px] text-slate-400"><span>Saúde da operação</span><Gauge className="h-4 w-4 text-cyan-300" /></div><p className="mt-3 font-mono text-4xl font-bold tracking-[-.08em]">98,7<span className="text-xl">%</span></p><div className="mt-3 h-1.5 rounded-full bg-white/10"><div className="h-full w-[88%] rounded-full bg-emerald-400" /></div><p className="mt-2 text-[9px] text-slate-400">+1,2% nas últimas 24h</p></div><div className="rounded-xl border border-white/10 bg-[#0b2943] p-4"><div className="flex gap-2 text-[10px] font-bold text-amber-200"><Bot className="h-4 w-4" />Padrão encontrado</div><p className="mt-3 text-[13px] font-semibold leading-5">Queda de vazão no circuito de água gelada.</p><p className="mt-2 text-[10px] text-slate-400">Chiller 02 + bomba P-14 + temperatura</p></div></div>
    <div className="relative rounded-xl border border-amber-300/20 bg-amber-300/[.08] p-4"><div className="flex items-start gap-3"><CircleAlert className="mt-0.5 h-4 w-4 shrink-0 text-amber-300" /><div><p className="text-xs font-semibold text-amber-100">Atenção priorizada · impacto moderado</p><p className="mt-1 text-[11px] leading-5 text-slate-300">Vibração subiu 18% em 42 min. O sistema recomenda verificar o conjunto antes de resetar o chiller.</p></div></div></div>
    <div className="relative mt-5 rounded-xl bg-[#f4f8f8] p-4 text-[#173b55]"><div className="flex flex-wrap gap-2">{reads.map((item, i) => <button key={item[0]} onClick={() => setTab(i)} className={`rounded-full px-3 py-1.5 text-[10px] font-bold transition ${tab === i ? "bg-[#123b59] text-white" : "bg-[#e8f2f2] text-[#668391]"}`}>{item[0]}</button>)}</div><div className="mt-4 flex gap-3"><Sparkles className="mt-1 h-5 w-5 shrink-0 text-[#078da8]" /><div><p className="text-sm font-bold">{reads[tab][0]}</p><p className="mt-2 text-xs leading-6 text-[#607b89]">{reads[tab][1]}</p></div></div><div className="mt-4 flex gap-2 border-t border-[#dbe9ea] pt-3"><span className="rounded bg-[#e4f8f0] px-2 py-1 font-mono text-[9px] text-[#16896c]">confiança 91%</span><span className="rounded bg-[#fff3d8] px-2 py-1 font-mono text-[9px] text-[#b47716]">3 evidências</span></div></div>
  </div>;
}
function Outcome({ icon: Icon, value, title, text, dark = false }: { icon: typeof Gauge; value: string; title: string; text: string; dark?: boolean }) {
  return <div className={`border-l pl-5 ${dark ? "border-cyan-300/40" : "border-[#9ddadd]"}`}><Icon className={`h-5 w-5 ${dark ? "text-cyan-300" : "text-[#078da8]"}`} /><p className={`mt-6 font-mono text-4xl font-bold tracking-[-.08em] ${dark ? "text-cyan-300" : "text-[#102d4a]"}`}>{value}</p><p className={`mt-2 text-[12px] font-bold ${dark ? "text-white" : "text-[#173b55]"}`}>{title}</p><p className={`mt-1 text-[11px] leading-5 ${dark ? "text-slate-400" : "text-[#69818d]"}`}>{text}</p></div>;
}
export function Consolidated() {
  const [menu, setMenu] = useState(false); const [dialog, setDialog] = useState(false); const [sent, setSent] = useState(false);
  const open = () => { setDialog(true); setSent(false); };
  const nav = [["BlueBee", "#bluebee"], ["Plataforma", "#plataforma"], ["Resultados", "#resultados"], ["Para quem opera", "#perfis"]];
  return <main className="min-h-[100dvh] overflow-x-hidden bg-[#f3f8f8] text-[#173b55]" style={{ fontFamily: "var(--font-sans)" }}>
    <style>{`.cb-grid{background-image:linear-gradient(rgba(29,104,124,.07) 1px,transparent 1px),linear-gradient(90deg,rgba(29,104,124,.07) 1px,transparent 1px);background-size:36px 36px}.cb-reveal{animation:cbIn .8s ease both}@keyframes cbIn{from{opacity:0;transform:translateY(14px)}to{opacity:1;transform:translateY(0)}}.cb-delay{animation-delay:.15s}`}</style>
    <header className="sticky top-0 z-40 border-b border-[#d8e6e8]/80 bg-[#f3f8f8]/90 backdrop-blur-xl"><div className="mx-auto flex h-[72px] max-w-7xl items-center justify-between px-5 sm:px-8 lg:px-10"><a href="#inicio"><Mark /></a><nav className={`${menu ? "absolute left-4 right-4 top-[68px] flex rounded-xl border border-[#d8e6e8] bg-[#f3f8f8] p-3 shadow-xl" : "hidden"} flex-col gap-1 md:static md:flex md:flex-row md:items-center md:gap-7 md:border-0 md:bg-transparent md:p-0 md:shadow-none`}>{nav.map(([label, href]) => <a key={href} href={href} onClick={() => setMenu(false)} className="rounded-lg px-3 py-2 text-xs font-semibold text-[#557180] hover:text-[#078da8]">{label}</a>)}<button onClick={open} className="mt-2 rounded-lg bg-[#123b59] px-4 py-2.5 text-xs font-bold text-white md:mt-0">Ver a operação <ArrowRight className="ml-1 inline h-3.5 w-3.5" /></button></nav><button onClick={() => setMenu(!menu)} className="rounded-lg border border-[#d8e6e8] p-2 md:hidden" aria-label="Abrir menu">{menu ? <X className="h-4 w-4" /> : <Menu className="h-4 w-4" />}</button></div></header>
    <section id="inicio" className="cb-grid relative overflow-hidden"><div className="absolute -right-40 top-20 h-[520px] w-[520px] rounded-full bg-cyan-200/30 blur-3xl" /><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 pb-20 pt-16 sm:px-8 lg:grid-cols-[.85fr_1.15fr] lg:px-10 lg:pb-28 lg:pt-24"><div className="cb-reveal relative z-10"><Label>inteligência para operações prediais</Label><h1 className="max-w-2xl text-[clamp(3.2rem,7vw,6.6rem)] font-bold leading-[.9] tracking-[-.08em] text-[#102d4a]">O prédio<br /><span className="text-[#078da8]">fala.</span> A equipe<br /><span className="text-[#e8a92c]">decide.</span></h1><p className="mt-7 max-w-lg text-[15px] leading-7 text-[#597483]">A Beeldings transforma sinais de campo em clareza operacional. Conecte infraestrutura, manutenção, segurança e performance — e veja o que merece resposta agora.</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={open} className="rounded-lg bg-[#e8a92c] px-5 py-3.5 text-sm font-bold text-[#173b55] shadow-[0_10px_22px_rgba(232,169,44,.2)] hover:-translate-y-0.5">Explorar uma situação real <ArrowRight className="ml-2 inline h-4 w-4" /></button><a href="#resultados" className="rounded-lg border border-[#c7dce1] px-5 py-3.5 text-sm font-bold text-[#315a6d]">Ver resultados</a></div><div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 border-t border-[#d5e5e8] pt-5 text-[10px] font-semibold text-[#6a828d]"><span><Check className="mr-1 inline h-3.5 w-3.5 text-[#12a886]" />SCADA + telemetria</span><span><Check className="mr-1 inline h-3.5 w-3.5 text-[#12a886]" />CFTV conectado</span><span><Check className="mr-1 inline h-3.5 w-3.5 text-[#12a886]" />Automação segura</span></div></div><div className="cb-reveal cb-delay relative"><ProofPanel /></div></div></section>
    <section id="bluebee" className="border-y border-[#d9e5e6] bg-[#eaf3f3] px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[.7fr_1.3fr] lg:px-2"><div><Label>o agente da operação</Label><h2 className="max-w-md text-4xl font-bold leading-[.96] tracking-[-.07em] sm:text-6xl">Não é mais um painel.<br /><span className="text-[#078da8]">É um parceiro</span> de decisão.</h2><p className="mt-6 max-w-md text-sm leading-7 text-[#527084]">BlueBee é a camada de entendimento da Beeldings: investiga padrões, preserva a evidência e sugere o próximo passo sem substituir quem conhece o prédio.</p><div className="mt-8 space-y-3 text-xs font-semibold text-[#31536b]">{["Interpreta sinais no contexto do ativo","Explica causas com base no histórico","Sugere próximos passos verificáveis"].map(x => <p key={x}><span className="mr-3 inline-flex rounded-full bg-white p-1.5 text-[#078da8]"><Check className="h-3.5 w-3.5" /></span>{x}</p>)}</div></div><div className="rounded-2xl border border-[#c8dfe0] bg-[#fbfdfc] p-4 shadow-[0_24px_60px_rgba(20,68,87,.08)] sm:p-7"><div className="flex items-center gap-3 border-b border-[#e1eded] pb-5"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#d9f2f2] text-[#078da8]"><Bot className="h-5 w-5" /></span><div><p className="text-sm font-bold">BlueBee · análise operacional</p><p className="font-mono text-[9px] uppercase tracking-[.15em] text-[#7b98a2]">contexto conectado · 06:42 BRT</p></div><span className="ml-auto h-2 w-2 rounded-full bg-emerald-400" /></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{[["12","sinais cruzados"],["91%","confiança"],["01","ação sugerida"]].map(x => <div key={x[1]} className="rounded-xl bg-[#f1f7f7] p-4"><p className="font-mono text-2xl font-bold text-[#123b59]">{x[0]}</p><p className="mt-2 text-[10px] text-[#69818d]">{x[1]}</p></div>)}</div><div className="mt-4 rounded-xl border-l-2 border-amber-400 bg-[#fff8e8] p-4 text-xs leading-6 text-[#5f6870]">“A vibração subiu 18% em 42 minutos. Recomendo inspeção na próxima ronda e acompanhamento da tendência.”</div></div></div></section>
    <section id="plataforma" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><Label>uma malha, toda a operação</Label><h2 className="max-w-2xl text-4xl font-bold leading-[.98] tracking-[-.07em] text-[#102d4a] sm:text-6xl">Do ponto de dados<br />ao próximo passo.</h2><div className="mt-14 grid gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4">{[{i:Network,t:"Contexto conectado",d:"Gateways, BACnet, Modbus, MQTT e CFTV em uma leitura contínua."},{i:CircleAlert,t:"Prioridade, não ruído",d:"Alarmes correlacionados por ativo, impacto e histórico."},{i:LineChart,t:"Histórico que explica",d:"Cada sinal ganha uma linha do tempo com causas e recorrências."},{i:Zap,t:"Ação com controle",d:"Playbooks e comandos com aprovação, registro e limites."}].map(({i:Icon,t,d},n)=><article key={t} className={`border-t-2 pt-5 ${n===1?"border-amber-400":"border-[#b8d9dc]"}`}><Icon className={`h-6 w-6 ${n===1?"text-amber-500":"text-[#078da8]"}`} /><p className="mt-7 font-mono text-[9px] font-bold tracking-[.17em] text-[#7b98a2]">0{n+1}</p><h3 className="mt-3 text-lg font-bold tracking-[-.03em]">{t}</h3><p className="mt-3 text-sm leading-6 text-[#668391]">{d}</p></article>)}</div></section>
    <section id="resultados" className="bg-[#123754] px-5 py-20 text-white sm:px-8 lg:py-28"><div className="mx-auto max-w-7xl lg:px-2"><div className="grid gap-14 lg:grid-cols-[.75fr_1.25fr]"><div><Label light>o que muda na prática</Label><h2 className="max-w-md text-4xl font-bold leading-[.96] tracking-[-.07em] sm:text-6xl">Resultado que aparece<br /><span className="text-cyan-300">na rotina e no caixa.</span></h2><p className="mt-6 max-w-sm text-sm leading-7 text-slate-300">Quando a equipe entende antes, a operação reage melhor: menos improviso, mais disponibilidade e decisões que podem ser explicadas.</p></div><div className="grid gap-9 sm:grid-cols-2"><Outcome dark icon={Clock3} value="14 min" title="até o reconhecimento" text="indicador observado em incidentes de alta prioridade" /><Outcome dark icon={BarChart3} value="32%" title="menos alarmes repetidos" text="potencial com correlação por contexto e recorrência" /><Outcome dark icon={Gauge} value="99,4%" title="disponibilidade acompanhada" text="em ambientes monitorados no período" /><Outcome dark icon={Wrench} value="R$ 87,5 mil" title="Redução de Custo potencial" text="estimativa ilustrativa por ciclo, evitando intervenções emergenciais e downtime" /></div></div><div className="mt-16 border-t border-white/15 pt-6"><p className="max-w-3xl text-sm leading-7 text-slate-300">Redução de custo não é promessa automática. É a consequência potencial de detectar anomalias mais cedo, priorizar melhor a manutenção, reduzir paradas e responder rápido — sempre validada contra a realidade de cada portfólio.</p><p className="mt-3 font-mono text-[9px] uppercase tracking-[.16em] text-cyan-300">indicadores potenciais / observados · não garantidos</p></div></div></section>
    <section id="perfis" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><Label>uma operação, várias decisões</Label><h2 className="text-4xl font-bold leading-[.96] tracking-[-.07em] sm:text-5xl">Cada pessoa vê<br /><span className="text-[#078da8]">o que precisa.</span></h2><p className="mt-6 max-w-sm text-sm leading-7 text-[#607b89]">Gestão, manutenção e segurança compartilham a mesma evidência, cada um no seu ritmo de decisão.</p></div><div className="space-y-3">{[{I:Gauge,t:"Gestão",d:"Disponibilidade, tendência, risco e impacto financeiro."},{I:Wrench,t:"Manutenção",d:"Causas prováveis, evidências e próximo passo sugerido."},{I:ShieldCheck,t:"Segurança",d:"CFTV, acesso e alarmes em uma única linha do tempo."}].map(({I,t,d})=><div key={t} className="group flex items-center gap-5 rounded-2xl border border-[#d9e6e8] bg-white p-5 transition hover:-translate-y-0.5 hover:border-[#75cbd2] hover:shadow-lg sm:p-6"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-[#e7f4f5] text-[#078da8]"><I className="h-5 w-5" /></span><div><h3 className="font-bold">{t}</h3><p className="mt-1 text-sm leading-6 text-[#5e7383]">{d}</p></div><ArrowRight className="ml-auto h-4 w-4 text-amber-500 transition group-hover:translate-x-1" /></div>)}</div></div></section>
    <section id="contato" className="relative overflow-hidden bg-[#eaf3f3] px-5 py-20 sm:px-8 lg:py-28"><div className="absolute right-[-3%] top-10 h-72 w-72 rounded-full border border-cyan-400/30" /><div className="relative mx-auto flex max-w-7xl flex-col justify-between gap-8 md:flex-row md:items-end"><div><Label>próximo turno</Label><h2 className="max-w-2xl text-4xl font-bold leading-[.96] tracking-[-.07em] text-[#102d4a] sm:text-6xl">Quando o prédio<br /><span className="text-[#078da8]">falar, você entende.</span></h2></div><button onClick={open} className="rounded-lg bg-[#123b59] px-5 py-3.5 text-sm font-bold text-white hover:-translate-y-0.5">Agendar uma conversa <ArrowRight className="ml-2 inline h-4 w-4" /></button></div></section>
    <footer className="border-t border-[#d9e5e6] bg-[#eef6f5] px-5 py-8 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 sm:flex-row sm:items-center"><Mark /><p className="font-mono text-[9px] uppercase tracking-[.15em] text-[#78919b]">inteligência que mantém o edifício em movimento · 2024</p></div></footer>
    {dialog && <div className="fixed inset-0 z-50 grid place-items-center bg-[#0c2940]/75 p-5 backdrop-blur-sm" role="dialog" aria-modal="true"><div className="w-full max-w-md rounded-2xl border border-[#c8dfe0] bg-[#f7fbfb] p-7 shadow-2xl"><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#d9f2f2] text-[#078da8]"><Sparkles className="h-5 w-5" /></span><button onClick={() => setDialog(false)} aria-label="Fechar" className="rounded-lg p-2 text-[#668391] hover:bg-[#eaf3f3]"><X className="h-4 w-4" /></button></div>{sent ? <div className="mt-6 rounded-xl border border-[#9bd9c7] bg-[#e4f8f0] p-5 text-center"><Check className="mx-auto h-7 w-7 text-[#16896c]" /><p className="mt-3 text-sm font-bold text-[#176a58]">Solicitação registrada.</p><p className="mt-1 text-xs text-[#578276]">Este é um protótipo visual — nenhum dado foi enviado.</p></div> : <form onSubmit={(e) => { e.preventDefault(); setSent(true); }} className="mt-5 space-y-3"><h3 className="text-2xl font-bold tracking-[-.04em]">Coloque contexto na sua operação.</h3><p className="text-sm leading-6 text-[#668391]">Conte onde a Beeldings precisa ajudar primeiro.</p><label className="block pt-2 text-xs font-bold">Seu e-mail corporativo<input required type="email" placeholder="nome@empresa.com.br" className="mt-2 h-11 w-full rounded-lg border border-[#c8dfe0] bg-white px-3 text-sm outline-none focus:border-[#078da8]" /></label><select className="h-11 w-full rounded-lg border border-[#c8dfe0] bg-white px-3 text-sm"><option>Alarmes e ativos críticos</option><option>Redução de custo e downtime</option><option>Telemetria e disponibilidade</option><option>CFTV e segurança</option></select><button className="mt-2 w-full rounded-lg bg-[#e8a92c] py-3 text-sm font-bold text-[#17344f]">Quero ver a demonstração <ArrowRight className="ml-1 inline h-4 w-4" /></button></form>}</div></div>}
  </main>;
}
export default Consolidated;