// @ts-nocheck
import { useState, type ElementType, type ReactNode } from "react";
import {
  Activity, AlertTriangle, ArrowDownRight, ArrowUpRight, Bell, Building2,
  Camera, CheckCircle2, ChevronRight, Clock3, Cpu, Download, Filter,
  Gauge, History, LayoutDashboard, LogOut, Menu, Search, Server, Settings2,
  ShieldCheck, TrendingUp, WifiOff, X, Zap,
} from "lucide-react";

const gateways = [
  { name: "Gateway Principal SP", id: "GW-SP-01", status: "online", cpu: 45, mem: 60, disk: 30, last: "agora" },
  { name: "Gateway Edge RJ", id: "GW-RJ-02", status: "online", cpu: 85, mem: 92, disk: 75, last: "agora" },
  { name: "Gateway Legado MG", id: "GW-MG-01", status: "nodata", cpu: 0, mem: 0, disk: 0, last: "há 5 min" },
  { name: "Gateway Secundário PR", id: "GW-PR-03", status: "offline", cpu: 0, mem: 0, disk: 0, last: "há 2 horas" },
];
const clients = [
  ["Shopping Vale Sul", 15, 4], ["Hospital Santa Clara", 12, 1],
  ["Autobras S.A.", 8, 5], ["Condomínio Horizonte", 5, 2],
];
const chart = [6, 10, 14, 21, 17, 12, 18, 25, 20, 23, 19, 28];

function Brand({ compact = false }: { compact?: boolean }) {
  return <div className="flex items-center gap-2.5">
    <span className={`${compact ? "h-8 w-8" : "h-10 w-10"} relative block shrink-0 text-cyan-300`} aria-hidden>
      <svg viewBox="0 0 40 40" className="h-full w-full fill-none"><path d="M20 2.8 35.3 11.4v17.2L20 37.2 4.7 28.6V11.4L20 2.8Z" fill="currentColor" fillOpacity=".11" stroke="currentColor" strokeWidth="1.4"/><path d="m20 10 8.3 4.8v9.6L20 29.2l-8.3-4.8v-9.6L20 10Z" fill="currentColor" fillOpacity=".22" stroke="currentColor" strokeWidth="1.2"/><path d="M20 10v19.2M11.7 14.8 20 19.6l8.3-4.8" stroke="currentColor" strokeWidth="1.1"/></svg>
    </span>
    <span className={`${compact ? "text-xl" : "text-2xl"} font-semibold tracking-[-.05em] text-white`}>Beel<span className="text-cyan-300">dings</span></span>
  </div>;
}
function Spark({ values, color = "#5eead4" }: { values: number[]; color?: string }) {
  const max = Math.max(...values); const min = Math.min(...values); const range = max - min || 1;
  const points = values.map((v, i) => `${(i / (values.length - 1)) * 58},${22 - ((v - min) / range) * 18}`).join(" ");
  return <svg viewBox="0 0 58 24" className="h-6 w-[58px]"><polyline points={points} fill="none" stroke={color} strokeWidth="2" strokeLinecap="round"/></svg>;
}
function Pill({ children, tone = "cyan" }: { children: React.ReactNode; tone?: "cyan" | "red" | "amber" | "green" | "slate" }) {
  const colors = { cyan: "border-cyan-300/20 bg-cyan-300/10 text-cyan-200", red: "border-red-300/20 bg-red-300/10 text-red-200", amber: "border-amber-300/20 bg-amber-300/10 text-amber-200", green: "border-emerald-300/20 bg-emerald-300/10 text-emerald-200", slate: "border-white/10 bg-white/[.05] text-slate-300" };
  return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[.1em] ${colors[tone]}`}>{children}</span>;
}
function Panel({ children, className = "" }: { children: ReactNode; className?: string }) {
  return <section className={`rounded-2xl border border-white/[.09] bg-[#101e2e]/90 shadow-[0_18px_55px_rgba(2,14,28,.22)] ${className}`}>{children}</section>;
}

export function Moderna() {
  const [period, setPeriod] = useState("24h");
  const [filter, setFilter] = useState("Todos");
  const [menu, setMenu] = useState(false);
  const [notice, setNotice] = useState("");
  const filtered = gateways.filter((g) => filter === "Todos" || (filter === "Críticos" && g.status === "offline") || (filter === "Atenção" && g.status === "online" && g.cpu > 80) || (filter === "Sem dados" && g.status === "nodata"));
  return <div className="min-h-[100dvh] bg-[#071522] p-3 font-sans text-slate-200 selection:bg-cyan-300 selection:text-[#071522] sm:p-5 lg:p-7">
    <div className="mx-auto flex max-w-[1500px] overflow-hidden rounded-[24px] border border-white/10 bg-[#0b1928] shadow-2xl">
      <aside className="hidden w-[226px] shrink-0 flex-col border-r border-white/[.08] bg-[#091421] lg:flex">
        <div className="p-6"><Brand compact /></div>
        <div className="px-3"><p className="px-3 pb-3 font-mono text-[9px] uppercase tracking-[.2em] text-slate-500">Workspace</p>
          <button className="flex w-full items-center gap-3 rounded-xl bg-cyan-300/10 px-3 py-3 text-left text-xs font-semibold text-cyan-100"><LayoutDashboard className="h-4 w-4 text-cyan-300"/> Visão global <span className="ml-auto h-1.5 w-1.5 rounded-full bg-amber-300"/></button>
          <button onClick={() => setNotice("Área de clientes aberta nesta prévia.")} className="mt-1 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-xs text-slate-400 hover:bg-white/[.05] hover:text-white"><Building2 className="h-4 w-4"/> Clientes</button>
        </div>
        <div className="mt-8 px-3"><p className="px-3 pb-3 font-mono text-[9px] uppercase tracking-[.2em] text-slate-500">Módulos</p>
          {[[Bell, "Alarmes", "47"], [Cpu, "Dispositivos", "8,4k"], [History, "Auditoria", ""]].map(([Icon, label, count]) => <button key={String(label)} onClick={() => setNotice(`${label} selecionado.`)} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-xs text-slate-400 hover:bg-white/[.05] hover:text-white"><Icon className="h-4 w-4 text-slate-500"/>{label}<span className="ml-auto font-mono text-[10px] text-amber-300">{count}</span></button>)}
        </div>
        <div className="mt-auto border-t border-white/[.08] p-4"><div className="flex items-center gap-3 rounded-xl bg-white/[.04] p-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-cyan-300/15 text-xs font-bold text-cyan-200">AS</span><div className="min-w-0"><p className="text-xs font-semibold text-white">Ana Souza</p><p className="text-[10px] text-slate-500">Administradora</p></div><LogOut onClick={() => setNotice("Sessão demonstrativa encerrada.")} className="ml-auto h-4 w-4 cursor-pointer text-slate-500 hover:text-white"/></div></div>
      </aside>
      <main className="min-w-0 flex-1 bg-[radial-gradient(circle_at_90%_0%,rgba(34,211,238,.09),transparent_30%)]">
        <header className="flex flex-wrap items-center justify-between gap-3 border-b border-white/[.08] px-4 py-4 sm:px-7"><div className="flex items-center gap-3"><button onClick={() => setMenu(!menu)} className="rounded-lg border border-white/10 p-2 text-slate-400 lg:hidden"><Menu className="h-4 w-4"/></button><div><p className="font-mono text-[9px] uppercase tracking-[.18em] text-cyan-300/80">Centro de controle / 06 jun 2024</p><h1 className="mt-1 text-lg font-semibold tracking-[-.03em] text-white sm:text-xl">Visão global <span className="text-slate-500">— Todos os sites</span></h1></div></div><div className="flex items-center gap-2"><div className="hidden rounded-xl border border-white/10 bg-white/[.04] p-1 sm:flex">{["24h","7d","30d"].map((p) => <button key={p} onClick={() => setPeriod(p)} className={`rounded-lg px-3 py-1.5 font-mono text-[10px] ${period === p ? "bg-cyan-300/15 text-cyan-200" : "text-slate-500"}`}>{p}</button>)}</div><button onClick={() => setNotice("Filtros atualizados.")} className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/[.04] px-3 py-2 text-xs font-semibold text-slate-300 hover:border-cyan-300/40"><Filter className="h-3.5 w-3.5"/> <span className="hidden sm:inline">Filtros</span></button><button onClick={() => setNotice("Configurações demonstrativas.")} className="rounded-xl border border-white/10 p-2 text-slate-400 hover:text-white"><Settings2 className="h-4 w-4"/></button></div></header>
        {menu && <div className="border-b border-white/10 bg-[#0c1c2d] p-3 lg:hidden"><button className="w-full rounded-lg bg-cyan-300/10 p-3 text-left text-xs text-cyan-100">Visão global</button></div>}
        <div className="space-y-5 p-4 sm:p-7">
          <div className="grid gap-3 sm:grid-cols-3">{[["Alarmes ativos","47","+12%",Bell,"red"],["Aguardando ACK","18","−5%",Clock3,"amber"],["Dispositivos offline","12","+2",WifiOff,"amber"]].map(([label,value,trend,Icon,tone]) => <Panel key={String(label)} className="relative overflow-hidden p-4"><div className={`absolute inset-x-0 top-0 h-0.5 ${tone === "red" ? "bg-red-400" : "bg-amber-300"}`}/><div className="flex items-start justify-between"><div><p className="text-xs text-slate-400">{label}</p><p className="mt-2 font-mono text-3xl font-bold tracking-[-.08em] text-white">{value}</p></div><Icon className={`h-5 w-5 ${tone === "red" ? "text-red-300" : "text-amber-200"}`}/></div><div className="mt-4 flex items-end justify-between"><span className={`flex items-center gap-1 text-[10px] font-semibold ${tone === "red" ? "text-red-300" : "text-emerald-300"}`}>{tone === "red" ? <ArrowUpRight className="h-3 w-3"/> : <ArrowDownRight className="h-3 w-3"/>}{trend} vs. ontem</span><Spark values={chart.slice(3,10)} color={tone === "red" ? "#fca5a5" : "#fcd34d"}/></div></Panel>)}</div>
          <div className="grid gap-5 xl:grid-cols-[1.5fr_.8fr]"><Panel className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-[9px] uppercase tracking-[.18em] text-cyan-300">Telemetria consolidada</p><h2 className="mt-1 text-base font-semibold text-white">Alarmes ao longo do tempo</h2><p className="mt-1 text-xs text-slate-400">Distribuição por severidade · {period}</p></div><Pill tone="amber">Densidade alta</Pill></div><div className="mt-7 flex h-48 items-end gap-2 border-b border-l border-white/10 px-3 pb-0 pt-4">{chart.map((v,i) => <button key={i} onClick={() => setNotice(`Leitura ${v} no intervalo ${i + 1}.`)} className="group relative flex h-full flex-1 items-end"><span className="absolute -top-7 left-1/2 hidden -translate-x-1/2 rounded-md bg-white px-2 py-1 font-mono text-[9px] text-[#081522] group-hover:block">{v}</span><span className={`w-full rounded-t-md transition-opacity group-hover:opacity-70 ${i === 7 ? "bg-amber-300" : "bg-cyan-300/65"}`} style={{height:`${v/30*100}%`}}/></button>)}</div><div className="mt-2 flex justify-between font-mono text-[9px] text-slate-500"><span>00h</span><span>06h</span><span>12h</span><span>18h</span><span>agora</span></div></Panel><Panel className="relative overflow-hidden p-5"><div className="absolute -right-10 -top-10 h-40 w-40 rounded-full border border-cyan-300/10 bg-cyan-300/[.04]"/><Gauge className="h-6 w-6 text-cyan-300"/><p className="mt-8 font-mono text-4xl font-bold tracking-[-.08em] text-white">99,4<span className="text-lg text-slate-500">%</span></p><p className="mt-2 text-sm font-semibold text-slate-200">Disponibilidade global</p><p className="mt-1 text-xs text-slate-500">+0,8% no período selecionado</p><div className="mt-8 flex items-center gap-2"><Pill tone="green"><CheckCircle2 className="h-3 w-3"/> Sistema estável</Pill></div></Panel></div>
          <Panel><div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/[.08] p-5"><div><h2 className="text-base font-semibold text-white">Saúde dos gateways</h2><p className="mt-1 text-xs text-slate-400">Recursos e conectividade em tempo real</p></div><div className="flex gap-1.5">{["Todos","Críticos","Atenção","Sem dados"].map((item) => <button key={item} onClick={() => setFilter(item)} className={`rounded-lg px-2.5 py-1.5 text-[10px] font-semibold ${filter === item ? "bg-cyan-300/15 text-cyan-200" : "text-slate-500 hover:bg-white/[.05]"}`}>{item}</button>)}</div></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead className="bg-white/[.025] font-mono text-[9px] uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-3">Gateway</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Recursos</th><th className="px-5 py-3 text-right">Último contato</th></tr></thead><tbody className="divide-y divide-white/[.06]">{filtered.map((g) => <tr key={g.id} className="hover:bg-white/[.025]"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="rounded-lg bg-cyan-300/10 p-2 text-cyan-200"><Server className="h-4 w-4"/></span><div><p className="font-semibold text-slate-200">{g.name}</p><p className="font-mono text-[10px] text-slate-500">{g.id}</p></div></div></td><td className="px-5">{g.status === "online" ? <Pill tone="green"><CheckCircle2 className="h-3 w-3"/> Online</Pill> : g.status === "offline" ? <Pill tone="red"><X className="h-3 w-3"/> Offline</Pill> : <Pill tone="slate">Sem dados</Pill>}</td><td className="px-5">{g.status === "online" ? <div className="w-48 space-y-1.5">{[["CPU",g.cpu],["MEM",g.mem],["DISCO",g.disk]].map(([key,val]) => <div key={String(key)} className="flex items-center gap-2 font-mono text-[9px] text-slate-500"><span className="w-9">{key}</span><span className="h-1.5 flex-1 rounded-full bg-white/10"><span className={`block h-full rounded-full ${Number(val)>80?"bg-amber-300":"bg-cyan-300"}`} style={{width:`${val}%`}}/></span><span className="w-7 text-right text-slate-400">{val}%</span></div>)}</div> : <span className="text-slate-600">Métricas indisponíveis</span>}</td><td className="px-5 text-right text-slate-400">{g.last}</td></tr>)}</tbody></table></div></Panel>
          <div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><Panel className="p-5"><div className="flex items-center justify-between"><div><h2 className="text-base font-semibold text-white">Atenção por cliente</h2><p className="mt-1 text-xs text-slate-400">Locais com mais anomalias ativas</p></div><Search className="h-4 w-4 text-slate-500"/></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{clients.map(([name,alarm,offline]) => <button key={String(name)} onClick={() => setNotice(`${name} selecionado.`)} className="flex items-center justify-between rounded-xl border border-white/[.07] bg-white/[.025] p-3 text-left hover:border-cyan-300/30"><div><p className="text-xs font-semibold text-slate-200">{name}</p><p className="mt-1 text-[10px] text-slate-500"><span className="text-red-300">{alarm}</span> alarmes · <span className="text-amber-200">{offline}</span> offline</p></div><ChevronRight className="h-4 w-4 text-slate-600"/></button>)}</div></Panel><Panel className="p-5"><div className="flex items-center gap-2"><History className="h-4 w-4 text-cyan-300"/><h2 className="text-base font-semibold text-white">Atividade recente</h2></div>{["João Silva reconheceu 5 alarmes","Maria Costa forçou RESET no Chiller 02","Automação Night Mode disparada"].map((item,i)=><div key={item} className="mt-4 flex gap-3 border-l border-cyan-300/30 pl-3"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-cyan-300"/><div><p className="text-xs text-slate-300">{item}</p><p className="mt-1 font-mono text-[9px] text-slate-500">{["há 2 min","há 15 min","há 45 min"][i]}</p></div></div>)}</Panel></div>
          {notice && <button onClick={() => setNotice("")} className="fixed bottom-5 right-5 flex items-center gap-3 rounded-xl border border-cyan-300/30 bg-[#10283a] px-4 py-3 text-xs text-cyan-100 shadow-xl">{notice}<X className="h-3.5 w-3.5"/></button>}
        </div>
      </main>
    </div>
  </div>;
}